# Generated by Django 3.0.2 on 2021-07-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='contact',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='profession',
            field=models.CharField(default='Engineer', max_length=100),
        ),
    ]
