# Generated by Django 3.0.2 on 2021-07-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20210729_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(default='Resume', max_length=50),
        ),
    ]
